---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golangci/golangci-lint:v1.41.1
  commands:
  - golangci-lint run -v
  volumes:
  - name: gopath
    path: /go

- name: test
  image: golang:1.16
  commands:
  - go test -v -covermode=atomic -coverprofile=coverage.out ./...
  volumes:
  - name: gopath
    path: /go

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: codecov_token

services:
- name: nsq
  image: nsqio/nsq
  commands:
  - /nsqd

volumes:
- name: gopath
  temp: {}
