name: Run Testing
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      nsqd:
        image: appleboy/nsqd
        ports:
          - 4150:4150
          - 4151:4151

    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run Tests
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
